services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=test-secret-key-not-for-production-min-32
      - DATABASE_URL=sqlite:///./database/test_database.db
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
